/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tony;

/**
 *
 * @author Iddot
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkAlmacen = new javax.swing.JCheckBox();
        checkRRHH = new javax.swing.JCheckBox();
        checkProduccion = new javax.swing.JCheckBox();
        checkVenta = new javax.swing.JCheckBox();
        listaUsers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkAlmacen.setText("Almacen");
        getContentPane().add(checkAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        checkRRHH.setText("RRHH");
        getContentPane().add(checkRRHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        checkProduccion.setText("Producción");
        getContentPane().add(checkProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        checkVenta.setText("Ventas");
        checkVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVentaActionPerformed(evt);
            }
        });
        getContentPane().add(checkVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        listaUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Alegria", "Juan A", "Cecilia", "Lupita" }));
        listaUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaUsersActionPerformed(evt);
            }
        });
        getContentPane().add(listaUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Administración de Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, 550, 110));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Seleccione un usuario\n2. Seleccione los permisos\n3. de click en el botón Guardar");
        jTextArea1.setFocusable(false);
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 220, 70));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/flecha back.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/flecha back big.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaUsersActionPerformed
        
        if ("Admin".equals(listaUsers.getSelectedItem().toString())){

             checkVenta.setSelected(true);
             checkAlmacen.setSelected(true);
             checkRRHH.setSelected(true);
             checkProduccion.setSelected(true);

         }


        else if ("Alegria".equals(listaUsers.getSelectedItem().toString())){

             checkVenta.setSelected(true);
             checkAlmacen.setSelected(false);
             checkRRHH.setSelected(false);
             checkProduccion.setSelected(false);

         }
        
        
        else if ("Cecilia".equals(listaUsers.getSelectedItem().toString())){

             checkVenta.setSelected(false);
             checkAlmacen.setSelected(false);
             checkRRHH.setSelected(false);
             checkProduccion.setSelected(true);

         }


        else {

            checkVenta.setSelected(false);
            checkAlmacen.setSelected(false);
            checkRRHH.setSelected(false);
            checkProduccion.setSelected(false);

        }
     
        
    }//GEN-LAST:event_listaUsersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        this.dispose();
        
        menu ven4 = new menu();
        ven4.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVentaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_checkVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAlmacen;
    private javax.swing.JCheckBox checkProduccion;
    private javax.swing.JCheckBox checkRRHH;
    private javax.swing.JCheckBox checkVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> listaUsers;
    // End of variables declaration//GEN-END:variables
}
