/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas_jp;

/**
 *
 * @author pauli
 */
public class init extends javax.swing.JFrame {

    /**
     * Creates new form init
     */
    public init() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sopor = new javax.swing.JButton();
        vent = new javax.swing.JButton();
        client = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sopor.setBackground(new java.awt.Color(123, 104, 238));
        sopor.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        sopor.setForeground(new java.awt.Color(255, 255, 255));
        sopor.setText("SOPORTE TECNICO");
        sopor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soporActionPerformed(evt);
            }
        });
        getContentPane().add(sopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, 40));

        vent.setBackground(new java.awt.Color(123, 104, 238));
        vent.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vent.setForeground(new java.awt.Color(255, 255, 255));
        vent.setText("VENTAS");
        vent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventActionPerformed(evt);
            }
        });
        getContentPane().add(vent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, -1));

        client.setBackground(new java.awt.Color(123, 104, 238));
        client.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        client.setForeground(new java.awt.Color(255, 255, 255));
        client.setText("CLIENTES");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });
        getContentPane().add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 260, -1));

        jButton2.setBackground(new java.awt.Color(123, 104, 238));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("AYUDA");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 100, 40));

        jButton3.setBackground(new java.awt.Color(123, 104, 238));
        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SALIR");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 100, 40));

        jLabel5.setBackground(new java.awt.Color(123, 104, 238));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("DEPARTAMENTO DE VENTAS");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 240, 122)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 350, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventActionPerformed
        ventass newframe = new ventass(); 
        
        newframe.setVisible(true);
        
        this.dispose(); 

    }//GEN-LAST:event_ventActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        clientes newframe = new clientes(); 
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_clientActionPerformed

    private void soporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soporActionPerformed
        soporte newframe = new soporte(); 
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_soporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new init().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton client;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton sopor;
    private javax.swing.JButton vent;
    // End of variables declaration//GEN-END:variables
}
