package rrhh;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tony.conexion;

public class editar extends javax.swing.JFrame {
    
    
    conexion cc = new conexion();
    Connection cx = cc.conect();
    

    
    public editar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       /** try {
        DefaultTableModel modelo=new DefaultTableModel ();
        tabla.setModel(modelo);
        PreparedStatement ps=null;
        ResultSet rs=null;
        RRHH Con=new RRHH();
        java.sql.Connection con= Con.conect();
        
        String sql ="Select NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,FECHA_DE_NACIMIENTO, "
                + "DEPARTAMENTO, SEXO, FECHA_DE_INGRESO, ANTIGUEDAD From contrato ";
       System.out.println(sql);
        ps= con.prepareStatement(sql);
        rs= ps.executeQuery();
        ResultSetMetaData rsMD= rs.getMetaData();
        int cantidadColumnas =rsMD.getColumnCount();
        //modelo.addColumn("N.DE.EMPLEADO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO_PATERNO");
        modelo.addColumn("APELLIDO_MATERNO");
        modelo.addColumn("FECHA_DE_NACIMIENTO");
        modelo.addColumn("DEPARTAMENTO");
        modelo.addColumn("SEXO");
        modelo.addColumn("FECHA_DE_INGRESO");
        modelo.addColumn("ANTIGUEDAD");
        int[] anchos=  {100,100,100,50,100,20,50};
        for (int x=0;x<cantidadColumnas;x++)
        {
       tabla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        
        }
        while (rs.next()){
        Object [] filas =new Object[cantidadColumnas];
        for(int i=0; i<cantidadColumnas; i++)
        {filas [i] =rs.getObject(i + 1);
        }
        modelo.addRow(filas);
        }
        
        }
        catch(SQLException ex) {
        System.err.println(ex.toString());
        
        
        }
    try {
        tabla.setModel(modelo);
        PreparedStatement ps=null;
        ResultSet rs=null;
        RRHH  conn= new RRHH();
        java.sql.Connection con=conn.;
        
        
        
        String sql="SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_DE_NACIMIENTO, "
                + "DEPARTAMENTO, SEXO, FECHA_DE_INGRESO, ANTIGUEDAD FROM contrato";
     ps=con.prepareStatement(sql);
     rs=ps.executeQuery();
         
     ResultSetMetaData rsMd= (ResultSetMetaData) rs.getMetaData();
     int cantidadColumnas = rsMd.getColumnCount();
     
     modelo.addColumn("NOMBRE");
     modelo.addColumn("APELLIDO_PATERNO");
     modelo.addColumn("APELLIDO_MATERNO");
     modelo.addColumn("FECHA_DE_NACIMIENTO");
     modelo.addColumn("DEPARTAMENTO");
     modelo.addColumn("SEXO"); 
     modelo.addColumn("FECHA_DE_INGRESO");
     modelo.addColumn("ANTIGUEDAD");
      int[] anchos=  {100,100,100,50,100,20,50};
      for (int i=0;i<tabla.getColumnCount();i++){
      tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
      }
      while (rs.next()){
          Object[] filas= new Object[cantidadColumnas];
          for(int i=0; 1<cantidadColumnas;i++){
              filas[i]=rs.getObject(i+1);
          }modelo.addRow(filas);
      }
    }catch (SQLException ex){
        System.err.print(ex.toString());
    } */ 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        departamento = new javax.swing.JTextField();
        paterno = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        fingreso = new javax.swing.JTextField();
        antiguedad = new javax.swing.JTextField();
        fnacimento = new javax.swing.JTextField();
        BORRAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        BUSCAR = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(123, 104, 238));
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, 30));

        jLabel2.setBackground(new java.awt.Color(123, 104, 238));
        jLabel2.setText("APELLIDO PATERNO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 30));

        jLabel3.setBackground(new java.awt.Color(123, 104, 238));
        jLabel3.setText("APELLIDO MATERNO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 30));

        jLabel4.setBackground(new java.awt.Color(123, 104, 238));
        jLabel4.setText("FECHA DE NACIMENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 150, 30));

        jLabel5.setBackground(new java.awt.Color(123, 104, 238));
        jLabel5.setText("DEPARTAMENTO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 30));

        jLabel6.setBackground(new java.awt.Color(123, 104, 238));
        jLabel6.setText("SEXO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 150, 30));

        jLabel7.setBackground(new java.awt.Color(123, 104, 238));
        jLabel7.setText("FECHA DE INGRESO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, 40));

        jLabel8.setBackground(new java.awt.Color(123, 104, 238));
        jLabel8.setText("ANTIGUEDAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 150, 30));

        materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maternoActionPerformed(evt);
            }
        });
        jPanel1.add(materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 198, 30));

        departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoActionPerformed(evt);
            }
        });
        jPanel1.add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 198, 30));

        paterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paternoActionPerformed(evt);
            }
        });
        jPanel1.add(paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 198, 30));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 198, 30));

        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 198, 30));

        fingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fingresoActionPerformed(evt);
            }
        });
        jPanel1.add(fingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 198, 30));

        antiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiguedadActionPerformed(evt);
            }
        });
        jPanel1.add(antiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 198, 30));

        fnacimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnacimentoActionPerformed(evt);
            }
        });
        jPanel1.add(fnacimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 198, 30));

        BORRAR.setBackground(new java.awt.Color(123, 104, 238));
        BORRAR.setText("DESPEDIR");
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });
        jPanel1.add(BORRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 150, 60));

        jButton2.setBackground(new java.awt.Color(123, 104, 238));
        jButton2.setText("ACENDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 150, 60));

        SALIR.setBackground(new java.awt.Color(123, 104, 238));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jPanel1.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 150, 60));

        tabla.setBackground(new java.awt.Color(123, 104, 238));
        tabla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO DE EMPLEADO", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "FECHA DE NACIMIENTO", "DEPARTAMENTO", "SEXO", "FECHA DE INGRESO", "ANTIGUEDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 180));

        BUSCAR.setBackground(new java.awt.Color(123, 104, 238));
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 150, 60));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maternoActionPerformed

    private void departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoActionPerformed

    private void paternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paternoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void fingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fingresoActionPerformed

    private void antiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiguedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiguedadActionPerformed

    private void fnacimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnacimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnacimentoActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed

    }//GEN-LAST:event_BORRARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        menuRRHH ob=new  menuRRHH();
        ob.setVisible(true);
        dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_SALIRActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
/**PreparedStatement ps=null;
ResultSet rs=null;
try{
    RRHH objCon= new RRHH();
    Connection conn= (Connection) objCon.conect();
            
            
            
    int  Fila= tabla.getSelectedRow();
    String NOMBRE = tabla.getValueAt(Fila,0).toString();
    ps=conn.prepareStatement("SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_DE_NACIMIENTO, "
                + "DEPARTAMENTO, SEXO, FECHA_DE_INGRESO, ANTIGUEDAD FROM contrato WHERE NOMBRE=?");
    ps.setString(0, NOMBRE);
    rs=ps.executeQuery();
    while (rs.next()){
        nombre.setText(rs.getString("NOMBRE"));
        paterno.setText(rs.getString("APELLIDO_PATERNO"));
        materno.setText(rs.getString("APELLIDO_MATERNO"));
        fnacimento.setText(rs.getString("FECHA_DE_NACIMIENTO"));
        departamento.setText(rs.getString("DEPARTAMENTO"));
        sexo.setText(rs.getString("SEXO"));
        fingreso.setText(rs.getString("FECHA_DE_INGRESO"));
        antiguedad.setText("ANTIGUEDAD");
    }
    
}catch (SQLException ex){
    System.out.println(ex.toString());
}*/
    }//GEN-LAST:event_tablaMouseClicked

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
String campo=buscar.getText();
String where= "";
if (!"".equals(campo))
{
where = "WHERE NDEEMPLEADO ='"+campo+"'";
}
 try {
        DefaultTableModel modelo=new DefaultTableModel ();
        tabla.setModel(modelo);
        PreparedStatement ps=null;
        ResultSet rs=null;

        
        String sql ="Select NDEEMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,FECHA_DE_NACIMIENTO, "
                + "DEPARTAMENTO, SEXO, FECHA_DE_INGRESO, ANTIGUEDAD From contrato "+where;
       System.out.println(sql);
        ps= cx.prepareStatement(sql);
        rs= ps.executeQuery();
        ResultSetMetaData rsMD= rs.getMetaData();
        int cantidadColumnas =rsMD.getColumnCount();
        modelo.addColumn("NDEEMPLEADO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO_PATERNO");
        modelo.addColumn("APELLIDO_MATERNO");
        modelo.addColumn("FECHA_DE_NACIMIENTO");
        modelo.addColumn("DEPARTAMENTO");
        modelo.addColumn("SEXO");
        modelo.addColumn("FECHA_DE_INGRESO");
        modelo.addColumn("ANTIGUEDAD");
        int[] anchos=  {100,250,250,250,200,250,200,200,250};
        for (int x=0;x<cantidadColumnas;x++)
        {
        tabla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        
        }
        while (rs.next()){
        Object [] filas =new Object[cantidadColumnas];
        for(int i=0; i<cantidadColumnas; i++)
        {filas [i] =rs.getObject(i + 1);
        }
        modelo.addRow(filas);
        }
        
        }
        catch(SQLException ex) {
        System.err.println(ex.toString());
        
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BUSCARActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
       //         new editar().setVisible(true);
        //    }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JTextField antiguedad;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField departamento;
    private javax.swing.JTextField fingreso;
    private javax.swing.JTextField fnacimento;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField sexo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
